#!/bin/sh

config=""
if [ "$1" = "zuul" ]
then
  config=zuul_gw
else
  config=spring_gw
fi

echo "Gateway configuration: $config"

DEPLOY_DIR="deploy"

[ ! -d $DEPLOY_DIR ] && mkdir $DEPLOY_DIR

a=$(ls -d */)

for i in $a
do
  cd "$i" || exit

  if
  [ ! -f "pom.xml" ] ||
  { [ $config != spring_gw ] && [ "$i" = "alpe_cloud_gateway/" ]; } ||
  { [ $config != zuul_gw ] && [ "$i" = "alpe_zuul_gateway/" ]; }
  then
    cd ..
    continue
  fi

  echo "Run service ${i%/}"
  chmod +x mvnw
  bash mvnw spring-boot:run \
    > "../deploy/${i%/}-run.log" & \
    echo $! > "../$DEPLOY_DIR/${i%/}-run.pid" &

  cd ..
done