spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: testService
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test/**
        - id: eurekaSerice
          uri: ${EUREKA_SERVER:http://localhost:8761}
          predicates:
            - Path=/services/**
          filters:
            - StripPrefix=1
        - id: eurekaNoStrip
          uri: ${EUREKA_SERVER:http://localhost:8761}
          predicates:
            - Path=/eureka/**