zuul:
  routes:
    services-status:
      path: /eureka-dashboard/**
      url: ${EUREKA_SERVER:http://localhost:8761}/eureka-dashboard
    eureka:
      path: /eureka/**
      url: ${EUREKA_SERVER:http://localhost:8761}/eureka
    test:
      path: /test/**
      service-id: test-service
      strip-prefix: false
