# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Cloud Discovery service CI

on:
  push:
    branches: [ master ]
    paths:
      - 'alpe_cloud_discovery/**'
      - '.github/workflows/cloud_discovery.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'alpe_cloud_discovery/**'
      - '.github/workflows/cloud_discovery.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        working-directory: ./alpe_cloud_discovery
        run: mvn -B package -Dspring.profiles.active=test --file pom.xml

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: d3sandoval/cloud-foundry-action@1.1.1
        with:
          args: push -f alpe_cloud_discovery/manifest.yml
        env:
          CF_API: https://api.cf.eu10.hana.ondemand.com
          CF_USERNAME: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_TARGET_ORG: 6b6fe2b9trial_P00001trial
          CF_TARGET_SPACE: dev
